### ISSUE TITLE
Fails to load some resources from angular2 folder

### ISSUE THREAD

**Issue by chrisdwheatley** [dylanb/Axponents#1]
Steps to reproduce:
- clone the repository & `cd` into it
- clone the angular quickstart repository
- install `serve` globally
- run `serve -p 8000`
- navigate to http://localhost:8000/angular2/
- notice issues in console, see screenshot below

![screen shot 2015-03-25 at 09 43 47](https://cloud.githubusercontent.com/assets/894092/6821897/80470894-d2d3-11e4-92da-16563b7e7aca.png)

**Comment by dylanb** [comment]
You have to start the web server in the angular2 directory directly. Have not found a way to get the Angular 2 imports to work relative to whatever directory you start in. If you know a way, please suggest it.

**Comment by dylanb** [comment]
@swirlycheetah Made some modifications to the readme file https://github.com/dylanb/Axponents/commit/c94ca938ad33cb9f52204c6f311e1369e8291dd1

**Comment by chrisdwheatley** [comment]
Those readme changes clear up where my confusion was coming from. Thanks!
