### ISSUE TITLE
Is there any way to consume polymer components inside an angular 2 component ?

### ISSUE THREAD

**Issue by tkhemani** [dylanb/Axponents#2]
Hi @dylanb 

I tried consuming a polymer element in an angular 2.0 app, but couldn't get it to work. 

I'm simply Adding polymer paper button (https://www.polymer-project.org/0.5/docs/elements/#paper-button) in index.html (before angular 2 is loaded) and app.html (inside angular's component) by adding this:

< link rel="import" href="bower_components/paper-button/paper-button.html">
polymer button outside angular 2 component directive
The button shows up only in index.html but NOT inside app.html.

Am I missing something...My code is here: https://github.com/tkhemani/youtube-app/commit/ac2e3d236b9415f5a5048fc6b1c17d72bfae168b

_Having worked on both polymer and angular2, can you help me with this._

Thanks
@tarun_khemani ( tkhemani@gmail.com)

**Comment by dylanb** [comment]
@tarun_khemani I have not tried to get Polymer components to work inside Angular 2. Sorry!
